---
  - name: Patch the server and Reboot
    hosts: all
    tasks:

      - pause:
          seconds: 12
      
      - name: Get service facts
        service_facts:
        register: services_state

      - name: Check nodetool status
        tags: Patch
        shell: "nodetool status | grep -c UN"
        register: nodetool_status
        when: services_state.ansible_facts.services["cassandra"].state == "running"

      - name: Patch the server
        become: yes
        become_user: root
        tags: Patch
        shell: "yum -y update"
        when: nodetool_status.stdout is defined and nodetool_status.stdout == EXPECTED_STATUS

      - name: Instruct SSM Agent to reboot the instance
        tags: reboot
        become: yes
        become_user: root
        shell: "exit 194"
        register: result
        when: nodetool_status.stdout is defined and nodetool_status.stdout == EXPECTED_STATUS
        failed_when: result.rc == 0
